#!/usr/bin/env python3
"""One-off: fill missing text_cas/text_val translations via Haiku.

Idempotent: skips entries that already have the required translation.
Saves after each entry for fault tolerance.
"""
from __future__ import annotations
import json
import os
import time
from pathlib import Path

import anthropic
import httpx
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent / ".env")
_api_key = os.environ.get("ANTHROPIC_API_KEY") or os.environ.get("ANTHROPIC")
if _api_key:
    os.environ["ANTHROPIC_API_KEY"] = _api_key

DATA = Path(__file__).parent.parent / "data" / "raw" / "interventions_raw.json"
client = anthropic.Anthropic(http_client=httpx.Client(trust_env=False))

PROMPT = """Tradueix el següent text d'una intervenció ciutadana al Ple de l'Ajuntament de València {direction}.

Regles estrictes:
- Mantén EXACTAMENT els mateixos paràgrafs (cada \\n del original és un \\n a la traducció).
- Mantén els marcadors de negreta **així** sobre les frases EQUIVALENTS (les mateixes idees clau).
- Si l'original conté noms censurats com [***], copia'ls tal qual sense traduir-los.
- Si l'original és mixt (parts en castellà i parts en valencià), tradueix tot al idioma destí.
- NO afegisques cap explicació ni comentari. Respon NOMÉS amb el text traduït.

TEXT ORIGINAL:
---
{text}
---

Tradueix només el text:"""


def translate(text: str, target: str) -> str | None:
    """target: 'cas' or 'val'"""
    direction = "al castellà" if target == "cas" else "al valencià"
    prompt = PROMPT.format(direction=direction, text=text)
    for attempt in range(3):
        try:
            msg = client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=8096,
                messages=[{"role": "user", "content": prompt}],
            )
            out = msg.content[0].text.strip()
            # Strip markdown fences if any
            if out.startswith("```"):
                out = out.split("\n", 1)[1] if "\n" in out else out
                if out.endswith("```"):
                    out = out.rsplit("```", 1)[0]
            return out.strip() or None
        except Exception as e:
            if "rate_limit" in str(e).lower() or "429" in str(e):
                wait = 30 * (attempt + 1)
                print(f" [rate limit, {wait}s]", end="", flush=True)
                time.sleep(wait)
            else:
                print(f" [API error: {e}]")
                return None
    return None


def needs_translation(iv: dict) -> list[str]:
    """Return list of missing translation targets ('cas' or 'val') for this entry."""
    idi = iv.get("idioma_original", "")
    cas = iv.get("text_cas") or ""
    val = iv.get("text_val") or ""
    missing = []
    if idi == "castellano" and not val:
        missing.append("val")
    if idi == "valenciano" and not cas:
        missing.append("cas")
    if idi == "mixt":
        if not cas:
            missing.append("cas")
        if not val:
            missing.append("val")
    return missing


def main():
    raw = json.loads(DATA.read_text())
    # Optional skip list (e.g. entries to be regenerated by re-extraction)
    skip_ids = set(os.environ.get("SKIP_IDS", "").split(",")) - {""}

    targets = []
    for iv in raw:
        if iv["id"] in skip_ids:
            continue
        miss = needs_translation(iv)
        for m in miss:
            targets.append((iv["id"], m))

    print(f"Missing translations: {len(targets)}")
    for tid, m in targets:
        print(f"  {tid}: text_{m}")

    if not targets:
        return

    by_id = {iv["id"]: iv for iv in raw}
    for tid, target in targets:
        iv = by_id[tid]
        text = iv.get("text_original") or ""
        if not text:
            print(f"SKIP {tid}: text_original empty")
            continue
        print(f"Translating {tid} → text_{target} ({len(text)}c) ...", end=" ", flush=True)
        out = translate(text, target)
        if not out:
            print("FAILED")
            continue
        iv[f"text_{target}"] = out
        print(f"OK ({len(out)}c)")
        # Save after each entry
        DATA.write_text(json.dumps(raw, ensure_ascii=False, indent=2))
        time.sleep(0.3)

    print("\nDone.")


if __name__ == "__main__":
    main()
